@extends('layout.master')
@section('title','assam')
@section('content')

<section class="breadcrumb-blog-version-one img-area">
   <div class="single-bredcurms banner_assam_desti">
      <div class="container">
         <div class="row">
            <div class="col-sm-12">
               <div class="bredcrums-content">
                  <h2>Assam</h2>
                  <ul>
                     <li><a href="{{('/')}}">Home</a></li>
                     <li class="active banner-fixed">Assam</li>
                  </ul>
               </div>
            </div>
         </div>
      </div>
   </div>
</section>
<!-- blog breadcrumb version one end here -->
<!-- Start blog -->
<section id="blog" class="section-paddings single section page">
   <div class="container">
      <div class="row">
         <div class="col-md-8 col-sm-12 col-xs-12">
            <div class="col-md-12">
               <!-- Single blog -->
               <div class="single-blog ">
                  <div class="blog-head">
                     <img src="{{('src/images/blog/assam.jpg')}}" alt="#" >
                  </div>
               </div>
               <!--/ End Single blog -->
            </div>
         </div>
         <div class="col-md-4 col-sm-12 col-xs-12">
            <!-- Blog Sidebar -->
            <div class="blog-sidebar">
               <!-- Single Sidebar -->
               <div class="single-sidebar category">
                  <h2>Destination of Northeast</h2>
                  <ul>
                     <li><a href="{{url('assam')}}"><i class="fa fa-angle-double-right"></i>Assam</a>
                     </li>
                     <li><a href="{{url('arunachlpradesh')}}"><i class="fa fa-angle-double-right"></i>Arunachl Pradesh</a>
                     </li>
                     <li><a href="{{url('meghalaya')}}"><i class="fa fa-angle-double-right"></i>Meghalaya</a>
                     </li>
                     <li><a href="{{url('nagaland')}}"><i class="fa fa-angle-double-right"></i>Nagaland</a>
                     </li>
                     <li><a href="{{url('manipur')}}"><i class="fa fa-angle-double-right"></i>Manipur</a>
                     </li>
                     <li><a href="{{url('mizoram')}}"><i class="fa fa-angle-double-right"></i>Mizoram</a>
                     </li>
                     <li><a href="{{url('tripura')}}"><i class="fa fa-angle-double-right"></i>Tripura</a>
                     </li>
                     <li><a href="{{url('sikkim')}}"><i class="fa fa-angle-double-right"></i>Sikkim</a>
                     </li>
                  </ul>
               </div>
               <!--/ End Single Sidebar -->
            </div>
            <!--/ End Blog Sidebar -->
         </div>
         <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="col-md-12">
               <div class="single-blog">
                  <div class="blog-content">
                     <h2 class="text-center under">Assam</h2>
                     <p class="paragraph">Assam is a beautiful and diverse state with an unbelievable range of cultures and landscapes. It is located in the northeast of India. Most Assam tourist spots - Misty Mountain of the people call it as a magic land while others call it as a green paradise. It divide it's borders in the North and East with the realm of Bhutan and Arunachal Pradesh. The State of Assam is one of the most beautiful regions of India. Assam has a rich heritage of culture and civilization. There are so many Assam tourist spots to visit for.</p>
                     <p class="paragraph"><strong>Kaziranga National Park:</strong> Home to two-thirds of the world&#39;s one horned rhinoceros population, this national park has been declared as a World Heritage Site. Jeep Safari and Elephant Safari is obviously the most preferred tourist
                     activity for the visitors to the Kaziranga National Park. However, there are many other tourist places apart from the Kaziranga NP which you can visit while holidaying in the Kaziranga. There is plenty of
                     nature getaways exists around the Kaziranga to be explored and enjoyed which are wildlife sanctuaries, Bird Sanctuaries, Waterfalls, Tea Estates, etc. If you are not holidaying with a time constraint then here are a few places around the Kaziranga where you must visit to get the memorable experience of the place and enjoy your holiday to the fullest.</p>
                     <p class="paragraph"><strong>Majuli:</strong> Majuli is a lush green environment friendly, pristine and pollution free fresh water island in the river Brahmaputra, just 20 km from the city of Jorhat. Majuli Island is inhabited by tribal and non-tribal communities of Assam. THe tribes here are the Mishings, Deoris and the Sonowal Kacharis with the Mishings having a dominant population. Majuli Island has 144 villages with a population of over 1,50,000.</p>
                     <p class="paragraph">One of the other famous site of the island, Kamalabari Satra, this religious site too houses significant articles related to art, culture, literature and classical studies.</p>
                     <p class="paragraph">Dakhinpat Satra was the chief satra patronized by the Ahom Ruler. This ancient educational centre is visited by thousand of devotees all throughout the year. Rasotsava, a prime festival of Assam, is celebrated with great enthusiasm and passion here.</p>
                     <p class="paragraph">One of the important attractions of Majuli, Gamur is among the many holy seats. Other prominent holy seats in the destination are Auniati, Daksinpath and Kamlabari. This Vaishnavite spot preserves ancient artifacts and articles, the most prominent among these being Bortop.</p>
                     <p class="paragraph">Tengapania is located on the banks of river Brahmaputra, Tengapania is a spectacular and popular picnic spot of the region. It is bounded by Dhakuakhana, Machkhoa and Disangmukh and is a major attraction for tourists and locals alike.</p>
                     <p class="paragraph">Auniati Satra is famous for its Apsara and Paalnaam dance, this centre was founded by Niranjan Pathakdeva and features a wide collection of traditional Assamese utensils, jewellery and handicrafts. Old utensils, jewellery and handicrafts are also housed in the centre.</p>
                     <p class="paragraph"><strong>Guwahati :</strong> Apart from having its own tourist spots, Guwahati also serves as an important base for many enjoyable holidays. Guwahati is a sprawling city beside the Brahmaputra River in the northeast Indian state of Assam. It’s known for holy sites like the Nilachal hilltop Kamakhya Temple, featuring shrines to the Hindu deities Shiva and Vishnu. To the east, 18th-century Navagraha Temple is an astronomical center with planetary shrines. Umananda Temple, dedicated to Shiva and covered with engravings, stands on Peacock Island in the river.</p>
                     <p class="paragraph"><strong>Hajo: </strong> The ancient pilgrim centre of Hajo is a unique place for being an attraction for three religions - Hindu, Muslims and Buddhists.</p>
                     <p class="paragraph">At a distance of about 24 km from the city of Guwahati, Hajo adores the banks of Brahmaputra. Shrines dedicated to Durga, Shiva, Vishnu, Buddha and major Muslim saints are found all over this place, making it an important pilgrimage center for people from all these three religions. The most famous temple is the Hayagriva Madhava Mandir which also attracts Buddhists as it is believed to be the site where Buddha attained Nirvana while the Powa Mecca Mosque finds popularity among Muslims.</p>
                     <p class="paragraph"><strong>Sivasagar: "Imprints of Ahom Dynasty"</strong> Dating back to the Ahom dynasty, this cultural town is full of historic tourist attractions from forts with underground architecture to numerous temples.</p>
                     <p class="paragraph">Sivasagar is a state of Assam that provides various tourist attractions related to architectural marvels, history and culture. Some of the most popular places here include a water tank called Bhorpukhuri along with Joysagar, a man-made lake, Ahom Museum, Rudrasagar tank and temples, Gaurisagar tank and temples. One can also visit the Kareng Ghar and the Rang Ghar.</p>
                     <p class="paragraph"><strong>Jorhat : </strong>Famous for its culture, mosques, tombs, gardens and most importantly - its tea plantations, Jorhat is also known as the tea capital of India.
                     </p>
                     <p class="paragraph">The cultural capital of Assam; home to the largest Tea research station; and Tea Capital of India - Jorhat might have multiple titles associated with it but the fact is that there's nothing like it in Assam. Inhabited by the people of different cultures, Jorhat has intriguing history to tell; it was the last capital of Ahom dynasty, which reigned supreme in Assam for more than six centuries. If you're on a holiday in Assam, make sure to get drenched in its exuberant culture, and visit ts famed attractions like Bangal Pukhuri, Thengal Manor, Burigosain Devalaya, Purnananda Buragohain Maidam, Bilvesvar Siva Temple, Magolu Khat, Dhekiakhowa Bornamghar and Raja Maidam.</p>
                     <p class="paragraph"><strong>Manas National Park :</strong> Manas National Park is a UNESCO Natural World Heritage site, a Project Tiger Reserve, an Elephant Reserve and a Biosphere Reserve in Assam. The only tiger reserve in Assam and also famous for the rare golden langur and the red panda, Manas is one of the best-kept national parks in India.</p>
                     <p class="paragraph">Manas is recognized not only for its rich biodiversity but also for its spectacular scenery and natural landscape which includes a range of forested hills, alluvial grasslands and tropical evergreen forests. It's home to India's second-largest tiger population. It is also famous for its population of the Wild water buffalo. Manas harbours the maximum number of endangered species from India as listed in the IUCN Red Book.</p>
                     <p class="paragraph">One can easily spot rhinos and tigers while sitting on an elephant. Forest officials arrange rides on elephants from Mathanguri for visitors to Manas. You can see tea pickers going about their job in groups during the tea season. Best time to see activity is October till first week of December and again from mid February onwards.</p>
                     <p class="paragraph"><strong>Dibrugarh: “Tea City of India” </strong> A major city in the north eastern region of India in line with cities like Guwahati and Bhubaneswar, Dibrugarh is the emerging communication and industrial hub of North East India. Renowned as the “Tea City of India”, Dibrugarh has been a popular travel destination of Assam for decades at a stretch. Along with tourism development, Dibrugarh is one of the major cities of India with massive growth in communication and industrial sector. Its economy thrives on 3 booming business: tea, oil and tourism.</p>
                     <p class="paragraph">One of the major attractions of Dibrugarh is dotted with numerous attractions and replete with a fair amount of things to do. The district is ideal for wildlife lovers who can satiate their wanderlust at the Jokai Botanical Garden cum Germplasm Center, Jeypore Rainforest, Dehing Patkai Wildlife Sanctuaries. And for those religious at heart, Dibrugarh has Shrikshetra Dhaam, Lord Jagannath Temple, Koli Aai Thaan, Dehing Satra and Buddhist Monastery at Namphake Village to imbibe spirituality.</p>
                     <p class="paragraph"><strong>Tinsukia :</strong> Tinsukia is quite popular with the tourists as it serves as the gateway to nearby beautiful villages and wildlife sanctuaries.</p>
                     <p class="paragraph">One of the popular tourist destinations in Assam, Tinsukia offers visitors a mix of fun, culture, and entertainment. This destination is rich in nature and has beautiful landscapes and stunning attractions to keep you occupied throughout your stay. Tinsukia situated in the upper easternmost part of Assam is considered as the commercial capital of Assam. Having the largest railway junction in Assam, Tinsukia is blessed with many places to visit that are all awe-inspiring and captivating. Tinsukia is truly a destination to visit when you visit Assam.</p>
                      <p class="paragraph">Tinsukia is a popular tourist destination in Assam and this place has many attractions to see and places to visit. Some worthy wildlife attractions to visit in Tinsukia are Dibru-Saikhowa National Park, Dehing Patkai Wildlife Sanctuary. Along with other attractions and places to visit near Tinsukia are like Bell Temple, Sadiya, Digboi, Lakhipathar to name a few.</p>
                     <p class="paragraph"><strong>Dibru Saikhowa National Park:</strong> It is a river island national park. It is one of the 19 biodiversity hotspots in the world. This National Park is situated 12 km north of Tinsukia in Assam. Of the seven parts of the park, one is a wetland and the rest is mainly covered with grasslands and dense forest. Dibru Saikhowa National Park is one of those places which boast of a rich collection of flora and fauna, many of them endangered. It is one of the few remaining protected sites in the Endemic Bird Area of the Assamese Plains.</p>
                     <p class="paragraph">Animal life to be viewed in their natural habitat includes royal Bengal tiger, hoolock gibbons and leopards, it is also home to some restricted-range species, such as the White-winged Wood Duck, Bengal Florican, Lesser Adjutant Stork, spotted-billed Pelican, White-bellied Heron, Pallas's Fish Eagle, Swamp Partridge, Jerdon's Babbler, Black-breasted Parrotbill and Striated Grassbird. Marsh Babbler, Swamp Prinia and Yellow Weaver. </p>
                     <p class="paragraph">There are no roads and hence no jungle safari or elephant rides for roaming in the park, so you can explore the park only by trekking, although boat service is available which can take you to various spots. Guijan Ghat and Saikhowa Ghat are the national park's entry points.</p>
                     <p class="paragraph"><strong>Nameri National Park: </strong> Nameri National Park is located in the Sontipur district of Assam, India. The park covers an area of 200 sq. km. and was built back in 1978. It is right at the foothills of eastern Himalayas and is around 35 kms from Tezpur which is the nearest town. The park is well-known for its diverse variety of flora and fauna. The place is an ideal habitat for animals such as tiger and elephant.</p>
                     <p class="paragraph">Nameri is also home to animals like Leopard, Bison, Sambar, Malayam Giant Squirrel, Muntjac , Hog Deer, Wild Boar, Wild Dog (Dhole), Sloth Bear, Himalayan Black Bear, Capped Langur, Malayam Giant Squirrel and many more. The park is also home to around 300 bird species and species like Hornbill, Barbets, Babblers, Bulbuls, Plovers, Ibis and Bee eaters.The national park also has Assam Roof Turtle, Multi-colored butterflies and Lantern fly. That is not all; Nameri national park is also home to the rare and endangered White Winged Wood Duck.</p>
                     <p class="paragraph">And that is not enough! Nameri National Park has a lot more to offer to all those who wish to have a closer look of nature. The forests of Nameri National Park have dense semi-evergreen forests, moist deciduous forests and riverine tracts. Travelers can also find cane and bamboo in the Nameri National Park. Also, they will find a wide variety of wild orchids at Nameri.</p>
                     <p class="paragraph"><strong>Sualkuchi: </strong> Sualkuchi is a small sleepy village that displays the culture and traditions of Assam in its best form. The village of Sualkuchi is only 35 km away from Guwahati. The nearest railway station to Sualkuchi is the Kamakhya railway station, only 30 km away from the village. Sualkuchi, a sleepy village in the northern bank of the river Brahmaputra is the center of Assam’s textile production, which has earned it the name of Manchester of India. The weaver’s village specializes in mainly two types of silk, Muga silk and Pat silk. Indigenous items such as mekhela chadors, and gamosas made of these materials are the famous produces in the country. It has been declared as a Handloom Heritage Village, and thus is steadily growing up as an important tourist spot in Assam. Eri silks and Endi clothes from this region is also quite well known. Sualkuchi Village is also quite rich in flora and fauna, and it retains the traditional charm with bamboo houses and overall rustic nature of the villages. A number of migratory birds visit the place during the winter season, and thus, bird watching is an ideal thing to do in Sualkuchi. There are a few budget hotels in the place with basic amenities for accommodation and the traditional cuisine is a must try. There are also various religious institutions like temples and namghars in the area which attract a number of tourists.</p>
                     <p class="paragraph">This weavers’ village amidst the lush greenery and the mountains is famous not only for the silk products, but also for scenic beauty of the land. The bio diversity of this place attracts nature lovers and photographers. Apart from this there are also temples like Siddheswar Devayala and satras like Hatisatra nearby, which enhances the appeal of the place.</p>
                     <p class="paragraph"><strong>Orang National Park: </strong>
                     One of the oldest game reserves of the state, The Orang National park located on the shores of river Brahmaputra, is home to various animals, birds, fishes and is one of the more popular tourist destinations of Assam. </p>
                     <p class="paragraph">Orang will pleasantly surprise you with its rich variety of animals, birds and fishes and a similar abundance in flora. The park is known for its rhinoceros conservation has The Great Indian Rhinoceros and the famous Bengal Tiger. Apart from rhinos, one will find here the Great Indian Rhinoceros, porcupines, Bengal tigers, civets, water buffaloes, leopards and many more. A huge number and types of fishes are also present here. Along with this you can spot a number of birds in the park such as kingfishers, fishing eagles, woodpeckers, mallards, white pelicans and so on. A safari into the park will let you experience the refreshing beauty of the surroundings and vegetation as well as the enjoyment of watching such variety of wildlife. The park is also an important breeding ground for various fishes.</p>
                      <p class="paragraph"><strong>Barpeta: </strong>
                     The land of Satras, Barpeta derives its names from “Bar” meaning big and “Peta” meaning pond. Hence, as the name suggests, Barpeta means ""land of big ponds"" and in old days, Barpeta was full of such ponds. Barpeta is the testimony of Srimanta Sankardeva and his able disciple Shri Madhabdeva who came from Upper Assam in the 16th century to lay down a strong foundation of Assamese Culture. This strong movement left behind a legacy, and that's why today one can see universities dealing with various branches of education and arts, including music, dance, drama, sculpture, ivory work and much more. When on a tour to Barpeta, make a point to visit satas that have influenced the lifestyle, and culture if people living here. Barpeta Satra, which is 500 years old, is a must visit. The park also offers close access to Manas National Park, a UNESCO world heritage site. </p>
                     <p class="paragraph"><strong>Pobitora Wildlife Sanctuary: </strong>Situated in the Morigaon district of Assam in the floodplains of River Brahmaputra, Pobitora Wildlife Sanctuary is known for high one-horned rhinoceros density. The sanctuary sprawls in an area of 38.8 sq kms out of which 16 sq kms is inhabited by the one-horned rhinos. Apart from the rhinos, Pobitora is home to a variety of other animals like leopard, wild boar, barking deer and wild buffalo and about 275 species of birds and various reptiles’ species as well. The reserve is also supports two critically Endangered, four Endangered, eight Vulnerable and three Near Threatened bird species. Marsh Babbler (Pellorneum palustre) is the state’s plains endemic bird species and can be found in great number in Pobitora. The perennial water bodies, which are also known as Beel are the breeding ground of variety of fishes and they even attract a sizable amount of migrant waterfowls along with many mammal species as well.</p>
                     <p class="paragraph">Pobitora Wildlife Sanctuary is only at a distance of about 48 kms from Guwahati, which is well-connected by air, rail and road by other major cities of India. Thus, one can first reach Guwahati and then hire a cab to reach Pobitora.</p>
                     <p class="paragraph"><strong>Umananda Island : </strong>The smallest river island in the world, Umananda Island is a place with legends aplenty, a place where man and the wilderness co-habit in peace and serenity. Umananda Island lies at the heart of the Mighty Brahmaputra River which flows through the middle of the city of Guwahati.</p>
                     <p class="paragraph">Umananda Temple in Guwahati is dedicated to Lord Shiva, located on an Island (Peacock Island) in the middle of Brahmaputra River. The temple is perched on a mountain called Bhasmakuta.</p>
                     <p class="paragraph">If legends are to be believed Lord Shiva resided here as Bhayananda. Name of the mountain has been derived from the story which says Lord Shiva burned Kamadeva into ashes when he interrupted Lord Shiva’s meditation.</p>
                     <p class="paragraph">The temple was commissioned in 1694 AD by King Gadadhar Singh. Umananda is the presiding deity of the temple. The annual festival of Siva Chaturdasi is the most important festival of the temple. It is believed if someone visits the temple and worships on the day when Amavasya falls on a Monday, gets blessed with happiness.</p>
                     <p class="paragraph"><strong>Mayong: ‘Land of Black Magic’ </strong>A majority of tourists visit different tourist places for a delightful landscape, weather, natural abundance, or for its historical significance. But there is a place in India that is becoming a popular tourist spot because of its art of magic and sorcery. It is none other than Mayong village in Assam that is also known as the ‘Land of Black Magic’ and located in Marigoan district on the banks of  the Brahmaputra River. Mayong village was the Indian Capital of Black Magic and Witchcraft even during the medieval period in ancient India. The village is situated close to the city of Guwahati. Now this magical history of the village is boosting tourism there.</p>
                     <p class="paragraph">It is believed that the name Mayong originated from the word Maya which means illusion. Also, it is said that when the whole of the northeastern region of India was one, Manipuri people used to reside there. At that time, the area was full of elephants and in Manipuri elephant is known as Miyong. So the village got its name that with time changed to Mayong.</p>
                     <p class="paragraph">A majority of tourists visit different tourist places for a delightful landscape, weather, natural abundance, or for its historical significance. But there is a place in India that is becoming a popular tourist spot because of its art of magic and sorcery. It is none other than Mayong village in Assam that is also known as the ‘Land of Black Magic’ and located in Marigoan district on the banks of  the Brahmaputra River. Mayong village was the Indian Capital of Black Magic and Witchcraft even during the medieval period in ancient India. The village is situated close to the city of Guwahati. Now this magical history of the village is boosting tourism there.</p>
                     <p class="paragraph">It is believed that the name Mayong originated from the word Maya which means illusion. Also, it is said that when the whole of the northeastern region of India was one, Manipuri people used to reside there. At that time, the area was full of elephants and in Manipuri elephant is known as Miyong. So the village got its name that with time changed to Mayong.</p>
                     <p class="paragraph">Till date, there are lots of texts in Mayong that are untapped and contain rich information about magic. Most of the families at Mayong village also possess these texts that are inherited from their ancestors. Some of the families have preserved these but some have destroyed these texts merely out of fear that these might fall into the wrong hands. People do not reveal the art of magic to anyone and keep this as a secret.</p>
                     <p class="paragraph">All these stories are now boosting tourism in Mayong, that is also a very striking place. Very close to the Brahmaputra River, in the lap of the nature, the village is rich in wildlife including flora and fauna. Government is now promoting tourism in Mayong for its culture and a nearby Pobitora Wildlife Sanctuary for the one-horned rhino.</p>
                     <p class="paragraph"><strong>Sadiya: </strong>It is situated in the Himalayan foothills, Sadiya is one of the sub-divisional headquarters of Tinsukia. It sits at the confluence of three three major rivers, Dihing (Tsangpo in Tibet), Dibang and Lohit that create the mighty Brahmaputra. </p>
                     <p class="paragraph">Sadiya is located in the eastern most part Assam which has few beautiful tourist sports frequently visited by tourists. Some of the tourist spots in Sadiya are Mayodia, Parsuram Kunda and Kibito located near around Arunachal Pradesh. There are also few historical places and temples near about Sadiya. Sadiya is also famous for a temple which is named Tameshwari. It is a Shakti Temple located in the centre of Assam and the temple can be reached after crossing the Brahmaputra River by ferries from the Dhola Ghat.  </p>
                     <p class="paragraph"><strong>Bogamati: </strong>Newly discovered Bogamati is a picturesque spot perfect for picnics that lies at the mouth of river ‘Barnadi’ on the foothills on Indo-Bhutan border, in the Baksa district, Assam. Inaugurated by Emanuel Muchahary, MLA of Tumulpur, about six years ago, the unexplored, panoramic view of the mountains.</p>
                     <p class="paragraph">The most popular tourist attraction of Baksa is Manas National Park, which is an important tourist destination in entire Assam. It has different species of animals and plants in abundance. It’s a paradise for bird watchers as well and many migratory birds visit this place during winter. You can also spot tigers, leopards, elephants, bisons, langurs etc. here.  </p>
                     <p class="paragraph">Moina Pukhuri is another place that you visit here. It is a trekking site and trekking through the rugged hills is an experience of a lifetime. Manas Soushi Khongkhor is yet another tourist destination in Baksa district that you can visit. It is an eco-tourism park that offers great view of the hills as well and has river nearby.</p>
                  </div>
               </div>
               <!--/ End Single blog -->
            </div>
         </div>
      </div>
   </div>
</section>
@endsection